version: 0.2

phases:
  install:
    commands:
      - apt-get update && apt-get install -y curl git openssh-client wget
      - echo Environment Vars and Version && echo $(env) && aws --version
      - env
  pre-build:
    commands:
      - wget "http://topman-public-bucket.s3.amazonaws.com/foo.txt"
