version: 0.2

phases:
  pre_build:
    commands:
      - apt-get update && apt-get install -y curl git openssh-client
      - echo Environment Vars and Version && echo $(env) && aws --version
      - env

